tei_edition:
    xsl:
        saxon:
            enabled: "%app.xsl_converter.saxonc_enable%"
        commandline:
            template: "%app.xsl_converter.commandline.template%"
        cache:  '@app.xslt_cache_pool'
    imagemagick:
        processor:
            path: "%app.imagemagick.processor.path%"
    pdf_generator:
        tempDir: "%kernel.project_dir%/var/cache/mpdf"
        fontDir: [ "%kernel.project_dir%/data/font" ]
        fontdata:
            book_typeface:
                R: 'WorkSans-Regular.ttf'
                B: 'WorkSans-Bold.ttf'
                I: 'WorkSans-Italic.ttf'
                BI: 'WorkSans-BoldItalic.ttf'
            # see https://github.com/OdedEzer/heebo/tree/master/compiled_fonts/ttf
            heebo:
                R: 'Heebo-Regular.ttf'
                B: 'Heebo-Bold.ttf'
                I: 'Heebo-Regular.ttf'
                BI: 'Heebo-Bold.ttf'
        fonttrans:
            'lora': book_typeface
            'jost': book_typeface
        default_font: book_typeface
